apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-frontend.fullname" . }}
spec:
  selector:
    app: {{ include "demo-frontend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
